name: boot-framework-build
on: [push]
jobs:
  maven_clean_deploy:
    name: Build and publish Repo
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'
          check-latest: true
          cache: gradle
      - name: Test with Gradle
        if: github.ref_type == 'branch' && !(startsWith(github.ref_name, 'release') || startsWith(github.ref_name, 'main'))
        run: gradle -Partifactory-password=${{ secrets.GITHUB_TOKEN }} -Partifactory-user=${{ github.actor }} publish
      - name: Release with Maven
        if: github.ref_type == 'branch' && (startsWith(github.ref_name, 'main'))
        run: git config user.email "release-bot@example.com" && git config user.name "release-bot" && mvn --batch-mode release:clean release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'com.framework.another.boot.another-framework'
          package-type: 'maven'
          min-versions-to-keep: 4
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'com.framework.another.boot.another-boot-observability-starter'
          package-type: 'maven'
          min-versions-to-keep: 4
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'com.framework.another.boot.another-boot-security-core'
          package-type: 'maven'
          min-versions-to-keep: 4
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'com.framework.another.boot.another-boot-starter'
          package-type: 'maven'
          min-versions-to-keep: 4
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'com.framework.another.boot.another-boot-starter-parent'
          package-type: 'maven'
          min-versions-to-keep: 4
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'com.framework.another.boot.another-boot-starter-webflux'
          package-type: 'maven'
          min-versions-to-keep: 4
    timeout-minutes: 10