name: boot-framework-build
on: [push]
  # push:
  #   branches:
  #     - 'release/*'
  #     - 'main'
jobs:
  maven_clean_publish:
    name: Publish-Framework-Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          check-latest: true
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots --show-version package
    timeout-minutes: 10
