name: boot-framework-build
on: [push]
jobs:
  maven_clean_verify:
    name: Build and Test Repo
    if: github.ref_type == 'branch' && startsWith(github.ref_name, 'feature')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          check-latest: true
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots --show-version verify
    timeout-minutes: 10